### ISSUE TITLE
5.0.0 Release

### ISSUE THREAD

**Issue by Andrewangeta** [vapor-community/StripeKit#21]
Branch collecting breaking changes to release in the next major version

(⚠️ = breaking changes)
- [x] ⚠️ Pin to API version 2019-12-03
- [x]   Add support for subscription schedules #18 
- [x]   ⚠️ `created` can't be optional anymore  #19 
- [x]   Add support for Webhooks endpoints #20 
- [x]   Add support for Events endpoints #22
